services:
  delivery-api:
    container_name: delivery-api

    build:
      context: .
      dockerfile: docker/backend.Dockerfile

    ports:
      - "8003:8000"

    volumes:
      - .:/app:Z

    depends_on:
      mysql:
        condition: service_healthy

    env_file:
      - ./backend/.env

    environment:
      ENV: docker

    restart: always

  mysql:
    container_name: mysql-shared

    image: mysql:8.0

    restart: always

    env_file:
      - ./backend/.env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:Z

  redis:
    container_name: redis

    image: redis:7-alpine

    restart: always

    ports:
      - "6379:6379"

volumes:
  mysql-data: