services:
  delivery-api:
    container_name: delivery-api

    build:
      context: .
      dockerfile: docker/backend.Dockerfile

    ports:
      - "8003:8000"

    volumes:
      - .:/app

    depends_on:
      - mysql

    env_file:
      - ./backend/.env

    environment:
      ENV: docker

    restart: always

  mysql:
    container_name: mysql-shared

    image: mysql:8.0

    restart: always

    env_file:
      - ./backend/.env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  redis:
    container_name: redis

    image: redis:7-alpine

    restart: always

    ports:
      - "6379:6379"

volumes:
  mysql-data: