services:
  delivery-api:
    container_name: delivery-api
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8003:8000"
    volumes:
      - .:/app:Z
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - shared-network

networks:
  shared-network:
    external: true