services:
  delivery-api:

    container_name: delivery-api

    build:
      context: .
      dockerfile: docker/backend.Dockerfile

    ports:
      - "8003:8000"

    volumes:
      - .:/app:Z

    depends_on:
      - delivery-db

    env_file:
      - ./backend/.env

    environment:
      ENV: docker

    restart: always

  delivery-db:

    container_name: delivery-db

    image: mysql:8.0

    restart: always

    env_file:
      - ./backend/.env

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-delivery}
      MYSQL_USER: ${MYSQL_USER:-delivery_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-delivery_password}

    ports:
      - "3010:3306"

    volumes:
      - delivery-db-data:/var/lib/mysql

volumes:
  delivery-db-data:
